Visual Studio Projects/PizzaSPAFinal/PizzaSPAFinal/Controllers/BuildPizzaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace PizzaSPAFinal.Controllers
{
    public class BuildPizzaController : Controller
    {
        // GET: BuildPizza
        public ActionResult Index()
        {
            return View();
        }
    }
}

Visual Studio Projects/PizzaSPAFinal/PizzaSPAFinal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace PizzaSPAFinal.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Visual Studio Projects/PizzaSPAFinal/PizzaSPAFinal/Views/Home/Index.cshtml
@section SPAViews {
    @Html.Partial("_Home")
}
@section Scripts{
    @Scripts.Render("~/bundles/knockout")
    @Scripts.Render("~/bundles/app")
}

Visual Studio Projects/PizzaSPAFinal/PizzaSPAFinal/Views/Home/_Home.cshtml
<!-- ko with: home -->
    <div class="jumbotron text-center" style="margin-top: 100px; margin-bottom: 100px; height: 600px; background-color: rgba(0, 0, 0, 0.91); color: #920a0a">
        <h1 style="margin-top: 50px; margin-bottom: 50px;">Academy Pizza</h1>
        <hr />
        <h2 style="margin-top: 80px;margin-bottom:80px;">Pizza Coded To Perfection!</h2>
        <hr />
        <div style="text-align: center; margin-top: 100px;">
            <button type="button" class="btn btn-lg btn-warning">
                @Html.ActionLink("Create Order", "Index", "BuildPizza")
            </button>
        </div>
    </div>


<!-- /ko -->